### ISSUE TITLE
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by mack4hack** [deshwalmahesh/NSE-Stock-Scanner#1]
Getting Issue while executing the pick()

**Preconditions**
Python 3

**Actual Result**

![image](https://user-images.githubusercontent.com/11089409/126461649-51d0f24a-48a2-4645-b3ae-fbd17155273c.png)

**Comment by deshwalmahesh** [comment]
It must be an unstable pull which you might have taken. Please take the latest pull and if it still exists, please do let me know.
