### ISSUE TITLE
ImportError: cannot import name 'PRIO_PROCESS' from 'os'

### ISSUE THREAD

**Issue by Pritam-Patra** [deshwalmahesh/NSE-Stock-Scanner#2]
![Image](https://user-images.githubusercontent.com/64914962/139303759-4eb586a2-c362-4066-bf7a-04fb7fc5a796.png)
How to fix this error? Kindly help

**Comment by deshwalmahesh** [comment]
This has been resolved. It was a testing bug. Please take the latest pull. Please let me know it it has been resolved or not.
